batch_id: 1
batch_size: 4
best_of: 8
c_puct: 1.25
enable_prefix_caching: true
errors_threshold: 3
few_shot_path: ./mcts_math/few_shots/math_examples.json
iterations: 40
max_depth: 20
mem_fraction_static: 0.5
mode: mcts
model_dir: ../AlphaMath-7B/
n_generate_sample: 8
need_value_func: true
num_few_shot: 0
prompt_path: ./mcts_math/few_shots/prompt.json
prompt_wrap: react_sft
question_range: 8
result_unwrap: react_sft
run_tool: sglang
seed: 42
step_delim: '

  '
stop:
- '

  </code>'
- </code>
- </step>
swap_space: 16
temperature: 0.6
update_leaf_value: false
verbose: false
